sudo: false
language: php

php:
  - 5.6

env:
  global:
    - DOCROOT=$TRAVIS_BUILD_DIR/../drupal
    - NIMBUS_DIR=$DOCROOT/themes/contrib/nimbus
    - NIMBUS_HALO_DIR=$DOCROOT/themes/custom/nimbus_halo

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.composer/vendor"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "$NIMBUS_DIR/node_modules"

mysql:
  database: drupal
  username: root
  encoding: utf8

# Set up environment.
before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini

  # Set up composer.
  - composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install drush
  - composer global require drush/drush:8.* --prefer-source
  - composer global require drupal/coder:8.* --prefer-source
  - phpenv rehash

  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*

  # Create MySQL Database
  - mysql -e 'create database drupal;'

  # Copy cached dependencies back to travis build dir so that they are
  # not wiped out by `drush dl drupal` command.
  - mv $NIMBUS_HALO_DIR/node_modules $TRAVIS_BUILD_DIR/

# Install Drupal and Nimbus itself.
install:
  # Install drupal default profile
  - cd ..
  - drush dl drupal --drupal-project-rename=drupal -y
  - cd drupal

  # Copy nimbus into themes/contrib/nimbus.
  - mkdir -p themes/contrib/nimbus
  - cp -R ${TRAVIS_BUILD_DIR}/* themes/contrib/nimbus/

  # Make custom dir for subtheme
  - mkdir -p themes/custom

  # Install Drupal and enable nimbus.
  - drush --verbose site-install minimal --db-url=mysql://root:@127.0.0.1/drupal --yes
  - drush en nimbus -y
  - drush nimbus "Nimbus Halo"

  # Set up front end dependencies.
  - cd $NIMBUS_HALO_DIR

  - ./install-node.sh 4.4.4
  - nvm use 4.4.4

  - npm run install-tools
  - npm rebuild node-sass

# Run nimbus tasks.
script:
  # Codesniff all files, ignore third party libraries and compiled CSS.
  - phpcs --standard=$HOME/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml --ignore=*/STARTERKIT/gulp-tasks/*,*/STARTERKIT/gulpfile.js,*/STARTERKIT/theme-settings.php,*/node_modules/*,*/styleguide/*,*/css/* $NIMBUS_DIR
  - phpcs --standard=$HOME/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml --ignore=*/gulp-tasks/*,gulpfile.js,*/node_modules/*,*/styleguide/*,*/css/* $NIMBUS_HALO_DIR

  - gulp
